/* Text to put at the beginning of the generated file. Probably a license. */

#ifndef PLATFORM_H
#define PLATFORM_H

/* Generated with cbindgen:0.27.0 */

/*
 * Warning, this file is autogenerated by cbindgen. Don't modify this manually.
 * Run this command to generate this file: cbindgen --config cbindgen.toml --output include/platform.h
 */


#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/*
 System color scheme, exposed across the C ABI.
 */
typedef enum Theme {
    Light,
    Dark,
} Theme;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Returns the current OS color scheme. Falls back to `Light` if the
 system theme cannot be determined (e.g. headless session / unsupported env).
 */
enum Theme get_system_theme(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* PLATFORM_H */
