use riti::keycodes::*;
use windows::Win32::UI::Input::KeyboardAndMouse::{
    VIRTUAL_KEY, VK_ADD, VK_DECIMAL, VK_DIVIDE, VK_MULTIPLY, VK_NUMPAD0, VK_NUMPAD1, VK_NUMPAD2,
    VK_NUMPAD3, VK_NUMPAD4, VK_NUMPAD5, VK_NUMPAD6, VK_NUMPAD7, VK_NUMPAD8, VK_NUMPAD9,
    VK_SUBTRACT,
};

pub const UNKNOWN_KEYCODE: u16 = 0;

pub fn to_keycode(ch: char, keycode: u32) -> u16 {
    let vk: VIRTUAL_KEY = VIRTUAL_KEY(keycode as u16);

    match (ch, vk) {
        // Keypad keys
        ('0', VK_NUMPAD0) => VC_KP_0,
        ('1', VK_NUMPAD1) => VC_KP_1,
        ('2', VK_NUMPAD2) => VC_KP_2,
        ('3', VK_NUMPAD3) => VC_KP_3,
        ('4', VK_NUMPAD4) => VC_KP_4,
        ('5', VK_NUMPAD5) => VC_KP_5,
        ('6', VK_NUMPAD6) => VC_KP_6,
        ('7', VK_NUMPAD7) => VC_KP_7,
        ('8', VK_NUMPAD8) => VC_KP_8,
        ('9', VK_NUMPAD9) => VC_KP_9,
        ('/', VK_DIVIDE) => VC_KP_DIVIDE,
        ('*', VK_MULTIPLY) => VC_KP_MULTIPLY,
        ('-', VK_SUBTRACT) => VC_KP_SUBTRACT,
        ('+', VK_ADD) => VC_KP_ADD,
        ('.', VK_DECIMAL) => VC_KP_DECIMAL,

        // Alphanumeric keys
        ('`', _) => VC_GRAVE,
        ('~', _) => VC_TILDE,
        ('0', _) => VC_0,
        (')', _) => VC_PAREN_RIGHT,
        ('1', _) => VC_1,
        ('!', _) => VC_EXCLAIM,
        ('2', _) => VC_2,
        ('@', _) => VC_AT,
        ('3', _) => VC_3,
        ('#', _) => VC_HASH,
        ('4', _) => VC_4,
        ('$', _) => VC_DOLLAR,
        ('5', _) => VC_5,
        ('%', _) => VC_PERCENT,
        ('6', _) => VC_6,
        ('^', _) => VC_CIRCUM,
        ('7', _) => VC_7,
        ('&', _) => VC_AMPERSAND,
        ('8', _) => VC_8,
        ('*', _) => VC_ASTERISK,
        ('9', _) => VC_9,
        ('(', _) => VC_PAREN_LEFT,

        // Alphabet Keys
        ('Q', _) => VC_Q_SHIFT,
        ('q', _) => VC_Q,
        ('W', _) => VC_W_SHIFT,
        ('w', _) => VC_W,
        ('E', _) => VC_E_SHIFT,
        ('e', _) => VC_E,
        ('R', _) => VC_R_SHIFT,
        ('r', _) => VC_R,
        ('T', _) => VC_T_SHIFT,
        ('t', _) => VC_T,
        ('Y', _) => VC_Y_SHIFT,
        ('y', _) => VC_Y,
        ('U', _) => VC_U_SHIFT,
        ('u', _) => VC_U,
        ('I', _) => VC_I_SHIFT,
        ('i', _) => VC_I,
        ('O', _) => VC_O_SHIFT,
        ('o', _) => VC_O,
        ('P', _) => VC_P_SHIFT,
        ('p', _) => VC_P,
        ('A', _) => VC_A_SHIFT,
        ('a', _) => VC_A,
        ('S', _) => VC_S_SHIFT,
        ('s', _) => VC_S,
        ('D', _) => VC_D_SHIFT,
        ('d', _) => VC_D,
        ('F', _) => VC_F_SHIFT,
        ('f', _) => VC_F,
        ('G', _) => VC_G_SHIFT,
        ('g', _) => VC_G,
        ('H', _) => VC_H_SHIFT,
        ('h', _) => VC_H,
        ('J', _) => VC_J_SHIFT,
        ('j', _) => VC_J,
        ('K', _) => VC_K_SHIFT,
        ('k', _) => VC_K,
        ('L', _) => VC_L_SHIFT,
        ('l', _) => VC_L,
        ('Z', _) => VC_Z_SHIFT,
        ('z', _) => VC_Z,
        ('X', _) => VC_X_SHIFT,
        ('x', _) => VC_X,
        ('C', _) => VC_C_SHIFT,
        ('c', _) => VC_C,
        ('V', _) => VC_V_SHIFT,
        ('v', _) => VC_V,
        ('B', _) => VC_B_SHIFT,
        ('b', _) => VC_B,
        ('N', _) => VC_N_SHIFT,
        ('n', _) => VC_N,
        ('M', _) => VC_M_SHIFT,
        ('m', _) => VC_M,

        ('-', _) => VC_MINUS,
        ('_', _) => VC_UNDERSCORE,
        ('=', _) => VC_EQUALS,
        ('+', _) => VC_PLUS,

        ('[', _) => VC_BRACKET_LEFT,
        (']', _) => VC_BRACKET_RIGHT,
        ('{', _) => VC_BRACE_LEFT,
        ('}', _) => VC_BRACE_RIGHT,
        ('\\', _) => VC_BACK_SLASH,
        ('|', _) => VC_BAR,

        (';', _) => VC_SEMICOLON,
        (':', _) => VC_COLON,
        ('\'', _) => VC_APOSTROPHE,
        ('\"', _) => VC_QUOTE,

        (',', _) => VC_COMMA,
        ('<', _) => VC_LESS,
        ('.', _) => VC_PERIOD,
        ('>', _) => VC_GREATER,
        ('/', _) => VC_SLASH,
        ('?', _) => VC_QUESTION,

        _ => UNKNOWN_KEYCODE,
    }
}
