name: CI
on: 
  push:
    branches: [ '**' ]
    tags-ignore: [ '**' ]
    paths-ignore: [ '**.md', '**.adoc' ]
  pull_request:
    branches: [ '**' ]
    paths-ignore: [ '**.md', '**.adoc' ]

jobs:
  build-linux:
    if: contains(github.event.head_commit.message, 'deploy+') == false
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        env:
          - { CXX: g++, CC: gcc, CXX_FOR_BUILD: g++, CC_FOR_BUILD: gcc }
          - { CXX: clang++, CC: clang, CXX_FOR_BUILD: clang++, CC_FOR_BUILD: clang }
    steps:
      - name: checkout-source
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: update-system
        run: sudo apt-get update -qq
      - name: install-deps
        run: sudo apt-get -y install build-essential clang cmake rustc cargo libibus-1.0-dev libfcitx5core-dev libzstd-dev qtbase5-dev qtbase5-dev-tools
      - name: make
        env: ${{ matrix.env }}
        run: |
          mkdir build
          cd build
          cmake .. -DENABLE_IBUS=ON -DENABLE_FCITX=ON
          make

  build-windows-x86_64:
    if: contains(github.event.head_commit.message, 'deploy+') == false
    runs-on: windows-latest
    steps:
      - name: checkout-source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: install-qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          arch: win64_msvc2019_64

      - name: build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE="$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows
          cmake --build . --config Release

  build-windows-arm:
    if: contains(github.event.head_commit.message, 'deploy+') == false
    runs-on: windows-11-arm
    steps:
      - name: checkout-source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: install-qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          arch: win64_msvc2019_arm64

      - name: setup-rust-target
        run: rustup target add aarch64-pc-windows-msvc

      - name: build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE="$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=arm64-windows -A ARM64
          cmake --build . --config Release

  build-macos:
    if: contains(github.event.head_commit.message, 'deploy+') == false
    runs-on: macos-latest
    steps:
      - name: checkout-source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: install-deps
        run: brew install cmake qt@5 zstd

      - name: setup-qt
        run: echo "$(brew --prefix qt@5)/bin" >> $GITHUB_PATH

      - name: build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_PREFIX_PATH="$(brew --prefix qt@5);$(brew --prefix zstd)"
          make

